# Name of the project
PROJ_NAME = Scientific_Calculator
TEST_PROJ_NAME = Test_$(PROJ_NAME)

BUILD_DIR = Build.exe

# All source code files
SRC =src/ADD.c\
src/SUBB.c\
src/multiply.c src/division.c src/factorial.c src/ src/power.c src/squareroot.c\
